[package]
name = "ospf_rust_physics"
version = "0.1.0"
edition = "2021"
authors = ["fuookami <fuookami@163.com>"]
description = "A physics utils for ospf-rust."
license = "MIT OR Apache-2.0"

[dependencies]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
